# Generated by Django 2.2 on 2020-04-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apprende', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcionCurso',
            field=models.TextField(blank=True, default='No hay descripcion', null=True),
        ),
    ]
