# Generated by Django 3.0.5 on 2020-05-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apprende', '0002_curso_descripcioncurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
