# Generated by Django 3.0.5 on 2020-05-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apprende', '0003_autor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(blank=True, default='No hay descripcion', null=True),
        ),
    ]
