# Generated by Django 2.2 on 2020-05-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apprende', '0004_autor_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
