# Generated by Django 2.2 on 2020-05-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apprende', '0005_curso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
